/// THIS FILE IS AUTOGENERATED. DO NOT MODIFY
use lazy_static::lazy_static;
use std::collections::BTreeMap;

lazy_static! {
    pub static ref IMAGE_MAP: BTreeMap<(u32, u32, u32), &'static str> = {
        let mut m = BTreeMap::new();
        m.insert((1, 14, 0), "sha256:db0a54476a8590ce2e0b7fee9ccc338604ffe12ba6edc29a2a4b41395338234b");
        m.insert((1, 14, 13), "sha256:d3fff488efc44fa7a91a695345939769bd71f3b44b027b3b9bae77520a24e6d3");
        m.insert((1, 14, 17), "sha256:0ca19fcf47b4216e7a85f0e6e356537389b69a1f198737abde437deeda9d1cff");
        m.insert((1, 16, 6), "sha256:8b4e4199e4363e6f5217a5e2167455fff81eb3dba7257fe37c47c6cf90218c34");
        m.insert((1, 16, 18), "sha256:75e506c42e0a6e78b5ef7e3b622d67c69932e48520d261849fe12f8c433228ea");
        m.insert((1, 16, 20), "sha256:359d7b849cf727cc2217548867f7f1b18faf663562b5b5cdd6c6daa76c7d5534");
        m.insert((1, 16, 23), "sha256:b3f79021e1a0d615855792a647a8c77f28a2dbbf9b3e85cc727ce21c65f80ee6");
        m.insert((1, 16, 26), "sha256:06dcfced3c0becb0c2162773a0770eea2a61f9f708a00db50002a363d76f2c69");
        m.insert((1, 17, 19), "sha256:9fb29c3477aef5879e42b2b70e944037cb95b91a69ea892db4dd05f1e404066c");
        m.insert((1, 17, 23), "sha256:2fccf5504f846400187b445ecc814ee2a974535385eb32738c8cd7e5664fc8df");
        m.insert((1, 17, 32), "sha256:e9933842425f94e49a3f8aff43ad380cbde6e1834bbb6ef53f4f714e6c1b8ad7");
        m.insert((1, 17, 33), "sha256:be84183e831d3ef9f7c2c91229b195204f12e3d06258b012adfca0ad9323977e");
        m.insert((1, 17, 34), "sha256:ece0a39259a3fe2444e30b472e83c84b21821be80942f438fd3257354ae6e943");
        m.insert((1, 18, 9), "sha256:78aaaa6f4c6f2ad047bf0bb8da5b3cc81c29c041061e885fcc05a30b4bf021e5");
        m.insert((1, 18, 12), "sha256:f571cb0325db3b80ddecdcac512f78639adf7778fb1d403280b1580073aa0df0");
        m.insert((1, 18, 13), "sha256:f97c4e14a0d50df7c19d45c56b201b20b95da13584c5aa1098201817ac2f6723");
        m.insert((1, 18, 14), "sha256:3c7d0ee2220cbc53807661e6efe7002b5bee9f9986f6a8aba858f08d2f7a9140");
        m.insert((1, 18, 15), "sha256:686f68ed858b89270461202aad1fbce64a973d3fd6ea7dcd5f1e66b10d12683a");
        m.insert((1, 18, 17), "sha256:1e5f78fad1f451737755555ec96c89643adce8b9b81272888d975518a98729fb");
        m.insert((1, 18, 18), "sha256:e7d469830494dfcdab2ae690d7b922d59e7e45c2ea6ee81b594d135c4ea4cfde");
        m.insert((1, 18, 19), "sha256:349f2068529027621f3856ade359525b0a97bf69f3d62bc06364b58fe720a767");
        m.insert((1, 18, 20), "sha256:2a48b17a34d5a53ceca01223390fbcc8f4003f5b0fc0b3fbb08c8cece5d26d43");
        m.insert((1, 18, 21), "sha256:a1c934490f3f39dfd49fefae3f80658432a171ddc9e068faada6a27b5e42ba1c");
        m.insert((1, 18, 22), "sha256:3c5885160c1a39be37709f4a76197537cc257aa796f65d1198b802f3928e4748");
        m.insert((1, 18, 23), "sha256:52575ee85ab3f7c8a46813a90eff7a88c2cdd8b206d0932afc6dc2e54c3cb8e0");
        m.insert((1, 18, 25), "sha256:38f256c288f97a11ba911085e0e6c525b9eb66cf7ca844a908035e4671f916d2");
        m.insert((1, 18, 26), "sha256:7daa61397d8613fd408bc81d5883cbc7054e7a9b943dfe7c6d768d0c02c45f8e");
        m
    };
}
